version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Maps port 80 on the host to port 80 in the container
      - "443:443"  # Maps port 443 on the host to port 443 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./public:/var/www/html
    depends_on:
      - app

  app:
    build: .
    container_name: nodejs_app
    ports:
      - "3000:3000"  # Ensure this line is present to map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
