version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./public:/var/www/html
    command: "/bin/bash -c 'while [ ! -f /etc/letsencrypt/live/decentralize.ooo/fullchain.pem ]; do echo Waiting for certificates; sleep 5; done; nginx -g \"daemon off;\"'"

  app:
    build: .
    container_name: nodejs_app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'certbot certonly --webroot --email draeder@gmail.com --agree-tos --no-eff-email --manual-public-ip-logging-ok --domain decentralize.ooo --http-01-port=80 --webroot-path=/var/www/certbot --keep; sleep 1d'"
    restart: unless-stopped
